In [57]:
import sys
import os

sys.path.append(
    os.path.abspath(".")
)

In [58]:
sys.path.append(
    os.path.abspath("..")
)

In [59]:
from src.datasets.brats_dataset import create_file_list
from src.transforms.preprocessing import (
    train_transform,
    val_transform
)
from torch_geometric.loader import DataLoader

In [60]:
from src.config import DATA_DIR

all_files = create_file_list(DATA_DIR)

print(len(all_files))

369


In [61]:
from sklearn.model_selection import train_test_split

train_files, val_files = train_test_split(
    all_files,
    test_size=0.2,
    random_state=42
)

print(len(train_files))
print(len(val_files))

295
74


In [62]:
from monai.data import Dataset

from src.transforms.preprocessing import (
    train_transform,
    val_transform
)

train_dataset = Dataset(
    data=train_files,
    transform=train_transform
)

val_dataset = Dataset(
    data=val_files,
    transform=val_transform
)

In [32]:
from src.graphs.create_graph_dataset import create_graph_dataset

print("Creating training graphs...")
train_graphs = create_graph_dataset(train_dataset)

print("Creating validation graphs...")
val_graphs = create_graph_dataset(val_dataset)

Creating training graphs...


  0%|          | 0/295 [00:00<?, ?it/s]d:\Internship\brats2020\src\graphs\graph_dataset.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.tensor(
  0%|          | 1/295 [00:01<07:02,  1.44s/it]d:\Internship\brats2020\src\graphs\graph_dataset.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.tensor(
  1%|          | 2/295 [00:02<06:30,  1.33s/it]d:\Internship\brats2020\src\graphs\graph_dataset.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.tensor(
  1%|          | 3/295 [

Creating validation graphs...


  0%|          | 0/74 [00:00<?, ?it/s]d:\Internship\brats2020\src\graphs\graph_dataset.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.tensor(
  1%|▏         | 1/74 [00:02<03:12,  2.64s/it]d:\Internship\brats2020\src\graphs\graph_dataset.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.tensor(
  3%|▎         | 2/74 [00:05<03:16,  2.74s/it]d:\Internship\brats2020\src\graphs\graph_dataset.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.tensor(
  4%|▍         | 3/74 [00:0

In [63]:
from torch_geometric.loader import DataLoader

train_loader = DataLoader(
    train_graphs,
    batch_size=1,
    shuffle=True
)

val_loader = DataLoader(
    val_graphs,
    batch_size=1,
    shuffle=False
)

In [35]:
from train_isgnn import train_isgnn

model = train_isgnn(
    train_loader,
    val_loader,
    epochs=300,
    lr=1e-3,
    hidden=128,
    patience=40
)

Epoch 000 | Train Loss: 0.4792 | Train Acc: 0.9363 | Val Loss: 0.3768 | Val Acc: 0.9790
Epoch 010 | Train Loss: 0.3755 | Train Acc: 0.9694 | Val Loss: 0.2997 | Val Acc: 0.9889
Epoch 020 | Train Loss: 0.3530 | Train Acc: 0.9723 | Val Loss: 0.2870 | Val Acc: 0.9893
Epoch 030 | Train Loss: 0.3383 | Train Acc: 0.9740 | Val Loss: 0.2786 | Val Acc: 0.9883
Epoch 040 | Train Loss: 0.3240 | Train Acc: 0.9750 | Val Loss: 0.2760 | Val Acc: 0.9888
Epoch 050 | Train Loss: 0.3142 | Train Acc: 0.9769 | Val Loss: 0.2737 | Val Acc: 0.9890
Epoch 060 | Train Loss: 0.3047 | Train Acc: 0.9779 | Val Loss: 0.2874 | Val Acc: 0.9892
Epoch 070 | Train Loss: 0.2967 | Train Acc: 0.9788 | Val Loss: 0.2664 | Val Acc: 0.9893
Epoch 080 | Train Loss: 0.2972 | Train Acc: 0.9788 | Val Loss: 0.2833 | Val Acc: 0.9898
Epoch 090 | Train Loss: 0.2901 | Train Acc: 0.9791 | Val Loss: 0.2838 | Val Acc: 0.9899

Early stopping at epoch 97

Training Complete
Best Validation Accuracy: 0.9903


In [ ]:
# from sklearn.model_selection import train_test_split

# train_files, temp_files = train_test_split(
#     all_files,
#     test_size=0.2,
#     random_state=42
# )

# val_files, test_files = train_test_split(
#     temp_files,
#     test_size=0.5,
#     random_state=42
# )

In [ ]:
# from src.datasets.brats_dataset import create_file_list
# from src.config import DATA_DIR
# from sklearn.model_selection import train_test_split

# all_files = create_file_list(DATA_DIR)

# # 80% train, 20% temp
# train_files, temp_files = train_test_split(
#     all_files,
#     test_size=0.2,
#     random_state=42
# )

# # Split temp into 10% val and 10% test
# val_files, test_files = train_test_split(
#     temp_files,
#     test_size=0.5,
#     random_state=42
# )

# print("Train:", len(train_files))
# print("Val  :", len(val_files))
# print("Test :", len(test_files))

Train: 295
Val  : 37
Test : 37


In [ ]:
# from monai.data import Dataset
# from src.transforms.preprocessing import val_transform

# test_dataset = Dataset(
#     data=test_files,
#     transform=val_transform
# )

In [ ]:
# from src.graphs.create_graph_dataset import create_graph_dataset

# print("Creating test graphs...")
# test_graphs = create_graph_dataset(test_dataset)

# print("Number of test graphs:", len(test_graphs))

Creating test graphs...


  0%|          | 0/37 [00:00<?, ?it/s]d:\Internship\brats2020\src\graphs\graph_dataset.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.tensor(
  3%|▎         | 1/37 [00:02<01:46,  2.95s/it]d:\Internship\brats2020\src\graphs\graph_dataset.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.tensor(
  5%|▌         | 2/37 [00:05<01:39,  2.84s/it]d:\Internship\brats2020\src\graphs\graph_dataset.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  edge_index = torch.tensor(
  8%|▊         | 3/37 [00:0

Number of test graphs: 37


In [64]:
from evaluate_isgnn import evaluate_isgnn

results = evaluate_isgnn(
    model,
    val_loader
)


===== Evaluation Results =====
Accuracy  : 0.5722
Precision : 0.2553
Recall    : 0.3681
F1 Score  : 0.1937

Confusion Matrix:

[[671699 365287 116009      0]
 [    33   3379    712      0]
 [     1  19735   1497      0]
 [     1   3686    407      0]]

Classification Report:

              precision    recall  f1-score   support

           0       1.00      0.58      0.74   1152995
           1       0.01      0.82      0.02      4124
           2       0.01      0.07      0.02     21233
           3       0.00      0.00      0.00      4094

    accuracy                           0.57   1182446
   macro avg       0.26      0.37      0.19   1182446
weighted avg       0.98      0.57      0.72   1182446


===== Dice Scores =====
Class 0: 0.7362
Class 1: 0.0171
Class 2: 0.0214
Class 3: 0.0000
