In [2]:
import sys
import os

sys.path.append(
    os.path.abspath(".")
)



In [3]:
sys.path.append(
    os.path.abspath("..")
)



In [4]:
from src.datasets.brats_dataset import create_file_list
from src.config import DATA_DIR
from src.transforms.preprocessing import (
    train_transform,
    val_transform
)

In [5]:
files = create_file_list(DATA_DIR)

print(len(files))

369


In [6]:
from sklearn.model_selection import train_test_split

files = create_file_list(DATA_DIR)

# 70% train
train_files, temp_files = train_test_split(
    files,
    test_size=0.30,
    random_state=42,
    shuffle=True
)

# 15% val, 15% test
val_files, test_files = train_test_split(
    temp_files,
    test_size=0.50,
    random_state=42,
    shuffle=True
)

print("Train:", len(train_files))
print("Val  :", len(val_files))
print("Test :", len(test_files))

Train: 258
Val  : 55
Test : 56


In [7]:
from monai.data import Dataset

train_ds = Dataset(
    data=train_files,
    transform=train_transform
)

val_ds = Dataset(
    data=val_files,
    transform=val_transform
)


In [8]:
from monai.data import DataLoader

In [9]:
train_loader = DataLoader(
    train_ds,
    batch_size=1,
    shuffle=True
)

val_loader = DataLoader(
    val_ds,
    batch_size=1,
    shuffle=False
)

In [10]:
batch = next(iter(train_loader))

print(type(batch))
print(batch.keys())

<class 'dict'>
dict_keys(['image', 'label'])


In [11]:
from models.unet_graph import UNetGraph
import torch

model = UNetGraph()

x = torch.randn(
    1,
    4,
    128,
    128,
    128
)

with torch.no_grad():
    y = model(x)

print(x.shape)
print(y.shape)

torch.Size([1, 4, 128, 128, 128])
torch.Size([1, 4, 128, 128, 128])


In [21]:
from train.train_unet_graph import train_unet_graph

model, history = train_unet_graph(

    train_loader,

    val_loader,

    epochs=30,

    lr=1e-4,

    patience=10

)


Device : cpu


Epoch 1/200
Batch 1/258 Loss 1.1268
Batch 6/258 Loss 1.0380
Batch 11/258 Loss 0.9823
Batch 16/258 Loss 0.9386
Batch 21/258 Loss 0.9025
Batch 26/258 Loss 0.8850
Batch 31/258 Loss 0.8930
Batch 36/258 Loss 0.8577
Batch 41/258 Loss 0.8307
Batch 46/258 Loss 0.7737
Batch 51/258 Loss 0.8276
Batch 56/258 Loss 0.7917
Batch 61/258 Loss 0.7210
Batch 66/258 Loss 0.7978
Batch 71/258 Loss 0.8061
Batch 76/258 Loss 0.8162
Batch 81/258 Loss 0.7222
Batch 86/258 Loss 0.7155
Batch 91/258 Loss 0.6930
Batch 96/258 Loss 0.7133
Batch 101/258 Loss 0.6443
Batch 106/258 Loss 0.7870
Batch 111/258 Loss 0.7386
Batch 116/258 Loss 0.7328
Batch 121/258 Loss 0.7017
Batch 126/258 Loss 0.6663
Batch 131/258 Loss 0.7393
Batch 136/258 Loss 0.7129
Batch 141/258 Loss 0.6579
Batch 146/258 Loss 0.6070
Batch 151/258 Loss 0.6790
Batch 156/258 Loss 0.7141
Batch 161/258 Loss 0.6639
Batch 166/258 Loss 0.6625
Batch 171/258 Loss 0.6841
Batch 176/258 Loss 0.6700
Batch 181/258 Loss 0.6959
Batch 186/258 Loss 0.7024
Batch 

KeyboardInterrupt: 

In [12]:
import torch

from models.unet_graph import UNetGraph
from evaluate_unet_graph import evaluate_unet_graph

device = torch.device(

    "cuda"

    if torch.cuda.is_available()

    else "cpu"

)

model = UNetGraph().to(device)

model.load_state_dict(

    torch.load(

        "best_unet_graph.pth",

        map_location=device

    )

)

evaluate_unet_graph(

    model,

    val_loader,

    device

)

Starting Evaluation
Device : cpu
Total batches : 55

Batch 1/55 ... 48.47 sec
Batch 2/55 ... 82.24 sec
Batch 3/55 ... 57.24 sec
Batch 4/55 ... 55.26 sec
Batch 5/55 ... 81.63 sec
Batch 6/55 ... 54.07 sec
Batch 7/55 ... 91.76 sec
Batch 8/55 ... 60.07 sec
Batch 9/55 ... 49.39 sec
Batch 10/55 ... 89.89 sec
Batch 11/55 ... 71.90 sec
Batch 12/55 ... 58.83 sec
Batch 13/55 ... 95.71 sec
Batch 14/55 ... 69.56 sec
Batch 15/55 ... 72.44 sec
Batch 16/55 ... 84.84 sec
Batch 17/55 ... 57.26 sec
Batch 18/55 ... 52.68 sec
Batch 19/55 ... 60.25 sec
Batch 20/55 ... 64.27 sec
Batch 21/55 ... 44.31 sec
Batch 22/55 ... 48.24 sec
Batch 23/55 ... 53.97 sec
Batch 24/55 ... 48.03 sec
Batch 25/55 ... 47.81 sec
Batch 26/55 ... 46.99 sec
Batch 27/55 ... 

: 

In [11]:
import torch

from models.unet_graph import UNetGraph
from evaluate_unet_graph import evaluate_unet_graph

device = torch.device(

    "cuda"

    if torch.cuda.is_available()

    else "cpu"

)

model = UNetGraph().to(device)

model.load_state_dict(

    torch.load(

        "best_unet_graph.pth",

        map_location=device

    )

)

evaluate_unet_graph(

    model,

    val_loader,

    device,

    max_batches=10

)

Starting Evaluation
Device : cpu
Evaluating first 10 batches only

Batch 1/10 ... 67.92 sec
Batch 2/10 ... 63.36 sec
Batch 3/10 ... 59.78 sec
Batch 4/10 ... 58.35 sec
Batch 5/10 ... 58.58 sec
Batch 6/10 ... 60.44 sec
Batch 7/10 ... 63.80 sec
Batch 8/10 ... 60.61 sec
Batch 9/10 ... 74.88 sec
Batch 10/10 ... 69.39 sec

Evaluation completed in 649.73 seconds

===== Evaluation Results =====
Accuracy  : 0.9946
Precision : 0.7756
Recall    : 0.7657
F1 Score  : 0.7673

Confusion Matrix:

[[88026905     4034    80633    10687]
 [   38211   243114   113865    10459]
 [  100875    56176   397295    38097]
 [   10895    18649     3347   126758]]

Classification Report:

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00  88122259
         1.0       0.76      0.60      0.67    405649
         2.0       0.67      0.67      0.67    592443
         3.0       0.68      0.79      0.73    159649

    accuracy                           0.99  89280000
   mac

{'accuracy': 0.9945572580645161,
 'precision': 0.7756078500260946,
 'recall': 0.7657057283485386,
 'f1': 0.767344944315232,
 'confusion_matrix': array([[88026905,     4034,    80633,    10687],
        [   38211,   243114,   113865,    10459],
        [  100875,    56176,   397295,    38097],
        [   10895,    18649,     3347,   126758]]),
 'classification_report': '              precision    recall  f1-score   support\n\n         0.0       1.00      1.00      1.00  88122259\n         1.0       0.76      0.60      0.67    405649\n         2.0       0.67      0.67      0.67    592443\n         3.0       0.68      0.79      0.73    159649\n\n    accuracy                           0.99  89280000\n   macro avg       0.78      0.77      0.77  89280000\nweighted avg       0.99      0.99      0.99  89280000\n',
 'wt': np.float64(0.8914857432254573),
 'tc': np.float64(0.7434834785590163),
 'et': np.float64(0.7334471285982719)}

In [ ]:
import torch

from models.unet_graph import UNetGraph
from evaluate_unet_graph import evaluate_unet_graph

device = torch.device(

    "cuda"

    if torch.cuda.is_available()

    else "cpu"

)

model = UNetGraph().to(device)

model.load_state_dict(

    torch.load(

        "best_unet_graph.pth",

        map_location=device

    )

)

evaluate_unet_graph(

    model,

    val_loader,

    device,

    max_batches=26

)